'use strict';

/** Falhas transitórias de rede/proxy no Chromium (vale retry / trocar sticky). */
const TRANSIENT_NET_MARKERS = [
  'ERR_TUNNEL_CONNECTION_FAILED',
  'ERR_PROXY_CONNECTION_FAILED',
  'ERR_SOCKS_CONNECTION_FAILED',
  'ERR_CONNECTION_RESET',
  'ERR_CONNECTION_CLOSED',
  'ERR_CONNECTION_ABORTED',
  'ERR_CONNECTION_REFUSED',
  'ERR_CONNECTION_FAILED',
  'ERR_CONNECTION_TIMED_OUT',
  'ERR_TIMED_OUT',
  'ERR_NETWORK_CHANGED',
  'ERR_EMPTY_RESPONSE',
  'ERR_RESPONSE_HEADERS_TRUNCATED',
  'ERR_SSL_PROTOCOL_ERROR',
  'ERR_SSL_VERSION_OR_CIPHER_MISMATCH',
  'ERR_BAD_SSL_CLIENT_AUTH_CERT',
  'ERR_CERT_COMMON_NAME_INVALID',
  'ERR_CERT_AUTHORITY_INVALID',
  'ERR_CERT_DATE_INVALID',
  'ERR_PROXY_AUTH_UNSUPPORTED',
  'ERR_PROXY_AUTH_REQUESTED',
  'ERR_NAME_NOT_RESOLVED',
  'ERR_NAME_RESOLUTION_FAILED',
  'ERR_ADDRESS_UNREACHABLE',
  'ERR_NETWORK_ACCESS_DENIED',
  'ERR_HTTP2_PROTOCOL_ERROR',
  'ERR_QUIC_PROTOCOL_ERROR',
  'ERR_SOCKET_NOT_CONNECTED',
  'ERR_HTTP_RESPONSE_CODE_FAILURE',
  'ERR_TOO_MANY_REDIRECTS',
];

/** Navegação que estourou timeout do Puppeteer também vale retry/rotação. */
const NAV_TIMEOUT_RE = /Navigation timeout|net::ERR_ABORTED|TimeoutError/i;

function isTransientProxyError(err) {
  const msg = String(err?.message || err || '');
  if (TRANSIENT_NET_MARKERS.some((m) => msg.includes(m))) return true;
  return NAV_TIMEOUT_RE.test(msg);
}

module.exports = { isTransientProxyError, TRANSIENT_NET_MARKERS };
